spring.application.name=Vitatech

# Configurações de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/vitatech_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Habilitar o Flyway explicitamente
spring.flyway.enabled=true